spring.application.name=commerce-payment-systems
spring.datasource.url=jdbc:mysql://localhost:3306/commerce
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
jwt.secret=your-very-long-secert-key-for-commerce-payment-system-2026
jwt.access-token-validity-ms=3600000

portone.base-url=https://api.portone.io

##강승규
#portone.store-id=store-9013fe91-c54c-4a7d-a78b-59e0ba7b1aa4
#portone.api-secret=tdTfiPOLvOEU12QoB8JjNHd18cXEGiS2qzlnzjYK2HbLVe0guYxWhduSV1H4Jw5iiuoyimRFDlH72mwD
#portone.channel-key=channel-key-eeb80ba4-e64e-4d27-b940-14bdcb7782a6
#portone.webhook-secret=whsec_lzoqdLPtEOI4J/+kP1V/VoahZWD/LkCsVytce4FjueM=


portone.store-id=store-6d678f00-d1a9-445d-b053-8a8f20692269
portone.api-secret=7gJ4LOoIqMN5NxmROFMgSC5m8yDcK7naMgy1ZbYJq36QLeKvdHUumTxQikU76444opBMQ8qwPE2Kgs49
portone.channel-key=channel-key-c9aee186-d91f-4aa8-a6bd-edfcde078d45
portone.webhook-secret=whsec_5/JaK/toZeUcWNvfq8L0pq0Y3a8gjdLArkE4ikWAR0g=